### ISSUE TITLE
Show upload progress bar while creating posts

### ISSUE THREAD

**Issue by singhpratyush** [hapramp/alpha-web#13]
Currently, when a post with an image is created, no progress bar is shown. The expected behavior is having a progress bar while uploading the image.

**Comment by gurjit03** [comment]
@singhpratyush do we have some form of data available that how much image is uploaded at each instant, then it shouldn't be that hard?

**Comment by singhpratyush** [comment]
We are moving away from this flow right now. I think this is no longer application.
