### ISSUE TITLE
Small font size

### ISSUE THREAD

**Issue by singhpratyush** [hapramp/alpha-web#16]
At many instances, font size if 12px (which is very small). These need to be updated to 14px.

**Comment by gurjit03** [comment]
Hey @singhpratyush I gonna begin with it :+1: 
For this I am thinking of creating a new directory for styles 
and adding font-sizes there.

**Comment by singhpratyush** [comment]
@gurjit03: We can go with updating the respective stylesheets for the components where we need to make the change.

**Comment by gurjit03** [comment]
@singhpratyush sure, but that might be quick fix to a long running problem. Standizing the font-sizes in entire application will help in long run and maintain the UX consistent across the application.

**Comment by singhpratyush** [comment]
We can save that with specifying in https://github.com/hapramp/alpha-web/blob/master/src/index.scss.

**Comment by gurjit03** [comment]
@singhpratyush actually this is exactly what I was saying to seperate out the configuration like variables and all in seperate file, under seperate directory.

**Comment by singhpratyush** [comment]
Coo. We can do that.
