### ISSUE TITLE
Reorganize package.json

### ISSUE THREAD

**Issue by singhpratyush** [hapramp/alpha-web#2]
`package.json` needs to be reorganized to separate different types of dependencies. For example, `webpack` based packages need to be moved to devDependencies.

**Comment by lalitmee** [comment]
Hey @singhpratyush, We can close this if no organization of packages is not required in `package.json`.

**Comment by singhpratyush** [comment]
Yeah, @lalitmee. Thanks for pointing out and resolving this issue.

Fixed in 6dfe3b935271996e5e70800a8a103ff8bdb5f0a0 (#121).

**Comment by lalitmee** [comment]
@singhpratyush, No problem. 
I would like to contribute more here.

**Comment by singhpratyush** [comment]
@lalitmee Sure! Just comment on the issue you would like to take on or open a new one if you feel like.
