### ISSUE TITLE
Implement code splitting

### ISSUE THREAD

**Issue by singhpratyush** [hapramp/alpha-web#24]
```
Creating an optimized production build...
Compiled successfully.

File sizes after gzip:

  670.64 KB  build/static/js/main.4c339acd.js
  3.88 KB    build/scss.5c41e27c.css
  3.88 KB    build/static/css/main.5c41e27c.css

The bundle size is significantly larger than recommended.
Consider reducing it with code splitting: https://goo.gl/9VhYWB
You can also analyze the project dependencies: https://goo.gl/LeUzfb
```

The bundle size has become large. The components need to be split properly in order to decrease the size and load only what's required in a view.

**Comment by gurjit03** [comment]
@singhpratyush I wanna take this issue ! Is there any specific choice of tools/methods/lib to handle code splitting, which you are considering ?

**Comment by singhpratyush** [comment]
I would prefer [`react-loadable`](https://github.com/jamiebuilds/react-loadable). But if you have some other alternative, you can proceed with it (or we can discuss if you want).

**Comment by gurjit03** [comment]
@singhpratyush lets close this :)
