### ISSUE TITLE
Integrate SteemConnect

### ISSUE THREAD

**Issue by singhpratyush** [hapramp/alpha-web#3]
There are two major issue in the app right now - 

1. Posting key is being stored in `localstorage`. This is not good as user's posting key can be stolen this way.

2. The login flow currently consists of creating a comment with a key and deleting it when it gets verified by the backend. This is an unnecessary step.

The above two and many more issues can be solved by using SteemConnect.

**Comment by aviaryan** [comment]
https://steemit.com/steemconnect/@noisy/how-to-configure-steemconnect-v2-and-use-it-with-your-application-how-it-works-and-how-it-is-different-from-v1
