### ISSUE TITLE
Unable to submit comment (Permlink is not a valid size)

### ISSUE THREAD

**Issue by tobias-g1** [hapramp/alpha-web#79]
#### Expected behavior

A user should be able to submit a comment for any given post. 

#### Actual Behaviour

When attempting to comment on a post, the comment is not submitted to the blockchain. 

#### Steps to reproduce

1. Go to https://alpha.1ramp.io/feed/
2. Sign in using your Steem Account
3. Go to https://alpha.1ramp.io/@ceeka-dacrafta/hb1jnkc00b4ddp6oq12wkamr55wkzmgg4hra1x2huqrzybrvm0gyv33amtss002t20181130100307
4. At the bottom, a comment bar is shown. Within the comment bar, attempt to submit a comment. For example "Test Comment"
5. Click send on the comment. 
6. Note that the comment is not submitted to the blockchain. 

#### Environment

- Browser: Google Chrome (Version 65.0.3325.162 (Official Build) (64-bit))
- Device: MacBook Pro (Retina, 15-inch, Late 2013)
- Operating system: MacOS HighSierra Version 10.13

#### Issues Details 

The following error is shown within the console:

```
steemconnect.com/api/broadcast:1 

Failed to load resource: the server responded with a status of 500 ()
```

Within the response from SteemConnect the following error is provided:

```
{"error":"server_error","error_description":"permlink.size() > STEEM_MIN_PERMLINK_LENGTH && permlink.size() < STEEM_MAX_PERMLINK_LENGTH: Permlink is not a valid size."}
```

The following request payload was used in the above request:

```
{"operations":[["comment",{"parent_author":"","parent_permlink":"","author":"tobias-g","permlink":"re---20181201t043845449z","title":"","body":"test comment","json_metadata":"{\"app\":\"hapramp/0.0.16\"}"}]]}
```

#### Recording of Issue

The following issue can be seen in the view below:

https://www.youtube.com/watch?v=3fpZrtEIoUg&feature=youtu.be

**Comment by singhpratyush** [comment]
Thanks for reporting @tobias-g1. This turned out to be a quick fix, wonder how I missed it :sweat_smile:.

**Comment by tobias-g1** [comment]
Awesome :) I can speak from first-hand experience, it's sometimes the ones that are right in front of you that sneak past. Glad it was useful :)

**Comment by 5310** [comment]
A followup—Even today (early 2021) we can't title works with some (most?) Unicode characters which throws this error at the final stage of publication. I tried with `æｓｔｈｅｔｉｃ 【﻿キャラ】`
